// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBookStoreManage.Data;

namespace WebBookStoreManage.Migrations
{
    [DbContext(typeof(WebBookStoreManageContext))]
    [Migration("20250219060902_editNVIENandNDUNGandaddTAIKHOAN")]
    partial class editNVIENandNDUNGandaddTAIKHOAN
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBookStoreManage.Models.LOAINHANVIEN", b =>
                {
                    b.Property<int>("IdLoaiNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLoaiNhanVien");

                    b.ToTable("LOAINHANVIEN");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.NGUOIDUNG", b =>
                {
                    b.Property<int>("IdNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.NHANVIEN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdLoaiNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdLoaiNhanVien");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.TAIKHOAN", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdNguoiDung")
                        .IsUnique()
                        .HasFilter("[IdNguoiDung] IS NOT NULL");

                    b.HasIndex("IdNhanVien")
                        .IsUnique()
                        .HasFilter("[IdNhanVien] IS NOT NULL");

                    b.HasIndex("IdVaiTro");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.VAITRO", b =>
                {
                    b.Property<int>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVaiTro");

                    b.ToTable("VAITRO");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.NHANVIEN", b =>
                {
                    b.HasOne("WebBookStoreManage.Models.LOAINHANVIEN", "LoaiNhanVien")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdLoaiNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNhanVien");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.TAIKHOAN", b =>
                {
                    b.HasOne("WebBookStoreManage.Models.NGUOIDUNG", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("WebBookStoreManage.Models.TAIKHOAN", "IdNguoiDung");

                    b.HasOne("WebBookStoreManage.Models.NHANVIEN", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("WebBookStoreManage.Models.TAIKHOAN", "IdNhanVien");

                    b.HasOne("WebBookStoreManage.Models.VAITRO", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.LOAINHANVIEN", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.NGUOIDUNG", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.NHANVIEN", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebBookStoreManage.Models.VAITRO", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
